### ISSUE TITLE
Doesn't detect deleted files

### ISSUE THREAD

**Issue by tfrommen** [researchgate/grunt-changed#1]
It would be nice if `grunt-changed` were capable of detecting deleted files, that is, if there is a cache entry for a file that doesn't exist anymore, make the task return `true`.

This would mean to change how `grunt-changed` works: loop through all cache entries and compare with the according file (**if it exists**), and not loop through all files and look up the according cache entry.

**Comment by bashofmann** [comment]
This is not in scope of the plugin. See also https://github.com/tschaub/grunt-newer/issues/15 for a related discussion. 

You could get this to work with https://www.npmjs.com/package/grunt-delete-sync
