### ISSUE TITLE
Task after `:changed` doesn't run the 2nd time even though it exited with an error the 1st time

### ISSUE THREAD

**Issue by ghost** [researchgate/grunt-changed#31]
Im trying to use grunt-changed together with grunt-eslint but running into a problem.

grunt-eslint is skipped the second time grunt-changed run when the source file hasn't changed, even though grunt-eslint exited with an error which should make grunt-changed to NOT cache the run as a successful run.

Im using the following task:
```
grunt.registerTask( 'js', [], function() {
	grunt.task.run(
		'changed:eslint:dev',
		'concat:jsDev'
	);
});
```

Reproduce by using grunt-eslint and grunt-changed and setup a task like above. Then knowingly create a syntax/lint error and run the task twice. The second time the eslint task will be skipped.

**Comment by swar30** [comment]
I'm having same issue, any work around ? 
Is this some thing that needs to be fixed in grunt-changed ? If yes I'm willing to try and fix it if some one will point me the right direction

**Comment by bashofmann** [comment]
I think I managed to fix the issue. The problem was that the hash was already written into the cache file before the wrapped task was executed and not after.

Can you test if the branch https://github.com/researchgate/grunt-changed/tree/write-hash-after-task fixes this for you @swar30 and @triggerjoi ?

If yes, I'll clean the code the up a bit (it's currently hacked in a bit) and merge it.

**Comment by swar30** [comment]
Sorry for late response, missed the notification, will try to check today

**Comment by swar30** [comment]
checked following scenarios
1. run task -> non breaking change -> run task (runs and passes)-> run task (skipped as expected)
2. run task -> breaking change -> run task (runs and fails as expected) -> run task (runs and fails as expected)
3. run task -> breaking change -> run task (runs and fails as expected) -> revert change -> run task (skipped and pass) 

The 3rd one I did not expect but when I think about it, it makes sense as reverted to last time when hash was for valid task.

Will be happy to see this change make it to released version and this time will try to not miss notificaions
