### ISSUE TITLE
Implement override

### ISSUE THREAD

**Issue by uefacomnewdev** [researchgate/grunt-changed#33]
The possibility to override the standard comparison mechanism is a very useful feature of grunt-newer it would be wonderful to have it also here. A common example is the less compilation where a file must be compiled even when is not modified itself but a dependency of it yes.

**Comment by bashofmann** [comment]
Good idea, feel free to create a pull request for it :)

**Comment by bashofmann** [comment]
Implemented by https://github.com/researchgate/grunt-changed/pull/37
