### ISSUE TITLE
changed not executing tasks on first run

### ISSUE THREAD

**Issue by joshuapetryk** [researchgate/grunt-changed#41]
Hello, we are experiencing an issue where changed tasks will not execute on a clean source directory on first run. Is this expected behavior? What will changed do if there is not a "last run"?

**Comment by bashofmann** [comment]
If there is no last run changed should just execute the task for everything. There is even a test case for this: https://github.com/researchgate/grunt-changed/blob/master/test/integration/fixtures/changed-clean-dest/gruntfile.js#L76

Maybe you are running in some kind of edge case. Can you provide a small reproducible test case for the problem you are experiencing?

**Comment by joshuapetryk** [comment]
Let me get back to you if this crops up again, may have been an issue with not having updated windows build tools. I don't have a reliable repro at this moment.
