### ISSUE TITLE
When used with uglify or cssmin, only uses changed files for input to tasks

### ISSUE THREAD

**Issue by jaydiablo** [researchgate/grunt-changed#7]
Based on the documentation, it seems that the uglify task should run on ALL input files defined in the config to generate the final minified file (which I assume is what most people would expect, not particularly useful to have an output file that doesn't contain the specified input files) regardless of which files changed, but in my testing that doesn't seem to be what is happening.  The changed plugin is acting more like how it's documented to act for tasks like "watch" or "jshint" because it's only passing the changed files into the uglify task.

Here's a sample uglify config that's being used:

```
uglify: {
                    options: {
                        compress: true,
                        mangle: true,
                        sourceMap: true
                    },
                    dev: {
                        /*files: [{
                            src: jsFiles,
                            dest: '<%= options.paths.js.dev %>'
                        }]*/
                        files: {
                            '<%= options.paths.js.dev %>': jsFiles
                        }
                    }
                },
```

`jsFiles` is a javascript array of JS file paths that should be used in the minification process.  I'm using a template for the destination file name.  I have a commented out files definition there because I was testing if it mattered if I used the array syntax or the object syntax that the changed documentation shows (it acts the same regardless of the definition).

I should mention that I am using a custom cache location in this config.

In the example in the Readme file, you use a glob pattern for the files, I haven't tested that yet in this case (but can't use it in this particular config. I may test it to see if it acts as expected though in that case, which I guess would point the finger at using an array as the src).

Anything obvious that I'm missing here?  Could it be the array input syntax that's getting filtered like it would for watch/jshint tasks?

The expected behavior here is that it won't filter the files input for this type of task no?

Using changed version 1.0.0 and grunt version 0.4.5 on node v0.10.36

**Comment by jaydiablo** [comment]
So I did test with a glob pattern that is similar to the example in the Readme file.  The glob was the only input into the files array, with a single file output (this is with uglify).

When I run with an empty cache, my output looks like this:

> Running "changed:uglify:dev" (changed) task
> 
> Running "uglify:dev" (uglify) task
> File js/main.min.js.map created (source map).
> File js/main.min.js created: 1.11 MB → 717.45 kB
> >> 1 sourcemap created.
> >> 1 file created.
> 
> Running "changed-postrun:uglify:dev:2" (changed-postrun) task

Then, when I run with the changed cache built, here's the output (after modifying just one JS file in the directory):

> Running "changed:uglify:dev" (changed) task
> 
> Running "uglify:dev" (uglify) task
> File js/main.min.js.map created (source map).
> File js/main.min.js created: 3.51 kB → 1.08 kB
> >> 1 sourcemap created.
> >> 1 file created.
> 
> Running "changed-postrun:uglify:dev:1" (changed-postrun) task

700kb to 1kb is excellent compression, unfortunately now my main.min.js file only contains the minified content of the single JS file that I modified.

I dug through the source of the task a little bit, and it really seems that this is the expected behavior, as the changed task re-configures the task that it calls if there are any files left after filtering from the cache so that the called task is only given the changed files, not the original source file list.

https://github.com/researchgate/grunt-changed/blob/master/tasks/changed.js#L93

If that's the intended behavior, then that's fine, it's useful for that purpose, but for these tasks that need all of the source files passed to the target task, but only want that task to run if **any** of those files have changed, this doesn't seem to work.

Based on the uglify example in the readme, it seems that this plugin is suitable for that use case, that's why I feel that I've done something wrong here.

**Comment by bashofmann** [comment]
I think I found what was missing: Can you test if this branch https://github.com/researchgate/grunt-changed/tree/issue_7_single_dest works for you. I'm not quite sure if the test case I wrote is really correct for what you are looking for

**Comment by jaydiablo** [comment]
I performed a similar test as I originally did for this ticket, and it does appear that the plugin is now sending all files to the uglify task, but only executing the uglify task if one or more of the source files have changed.

I have another task that uses grunt-changed that acts more like the watch task example you have, and that seems to still work as expected as well (though I don't act on any files, so I haven't confirmed that it's still only sending the modified files to such a task. I assume the tests cover such cases though).

Nice work!

**Comment by bashofmann** [comment]
Ok, merged it now to master. Thanks for reporting and your help with testing it.
